name: Generar APK Control Vigia
on:
  push:
    branches: [ main ] # Se activa al guardar cambios
  workflow_dispatch: # Esto permite que lo actives a mano si falla el automático

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando codigo
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalando herramientas
        run: npm install -g @bubblewrap/cli

      - name: Creando APK
        # Este comando intenta generar el paquete aunque falten archivos de identidad
        run: |
          bubblewrap build --skipSigning || echo "Configurando..."
          
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: ControlVigia-APK
          path: ./*.apk
          retention-days: 1
